INSERT INTO edomonike (alias,name) 
	VALUES
('memey','Memey'),
('brenda','Brenda'),
('drhsonya','drh. Sonya'),
('drhbintara','drh. Bintara'),
('drhsabila','drh. Sabila'),
('drhaisha','drh. Aisha'),
('drhtomi','drh. Tomi'),
('drhovi','Ovi Kawaii'),
('drhputri','drh. Putri'),
('kakpuspa','Kak Puspa'),
('drhaji','drh. Aji'),
('drhherlina','drh. Herlina'),
('drhmarchel','drh. Marchel'),
('drhirma','drh. Irma'),
('drhmusfian','drh. Musfian'),
('drhchandra','drh. Chandra'),
('kadevi','Ka Devi'),
('mbayuni','Mba Yuni'),
('tehyuni','Teh Yuni'),
('mbasiska','Mba Siska'),
('adeindah','Ade Indah'),
('alfiananda','Alfiananda'),
('anes','Anes'),
('drhricko','drh. Ricko'),
('pakbuafen','Pak Afen-Bu Ana'),
('budimia','Budi'),
('drhbayu','drh. Christophorus'),
('cilaura','Ci Laura'),
('cika','Cika'),
('drhagus','drh. Agus'),
('drhaldi','drh. Aldi'),
('drhreza','drh. Reza'),
('drhriza','drh. Riza'),
('drhvani','drh. Vani'),
('faisal','Faisal'),
('drhafi','drh. Afi'),
('drhagnes','drh, Agnes'),
('drhasyafia','drh. Asyafia'),
('drhbrigita','drh. Brigita'),
('drhchristina','drh. Christina'),
('drhdella','drh. Della'),
('drhdelsa','drh. Delsa'),
('drhdinda','drh. Dinda'),
('drhelin','drh. Elin'),
('drhelsa','drh. Elsa'),
('drherwin','drh. Erwin'),
('drhfahmi','drh. Fahmi'),
('drhgunawan','drh. Gunawan'),
('drhhani','drh. Hani'),
('drhhanum','drh. Hanum'),
('drhicha','drh. Icha'),
('drhjessica','drh. Jessica'),
('drhdzikria','drh. Dzikria'),
('drhgodelva','drh. Godelva'),
('drhkevin','drh. Kevin'),
('drhlabib','drh. Labib'),
('drhlaily','drh. Laily'),
('Maria','Maria'),
('drhmeifi','drh. Meifi'),
('drhnabiel','drh. Nabiel'),
('drhnindy','drh. Nindy'),
('drhnovi','drh. Novi'),
('novita','Novita'),
('nyoman','Nyoman Bagas'),
('paulina','Paulina'),
('drhradix','drh. Radix'),
('drhtitah','drh. Titah'),
('drhedo','drh. Ronaldo'),
('drhsasha', 'drh. Sasha'),
('drhulya','drh. Ulya'),
('drhvivin','drh. Vivin'),
('drhyude','drh. Yulia Dea'),
('drhyustia','drh. Yustia'),
('drhzevanya','drh. Zefanya'),
('ika','Ika'),
('intanifana','Intan Ifana'),
('jess','Jessica'),
('esterh','Ester Helena'),
('keziam','Kezia Merikel'),
('keziamil','Kezia Milenia'),
('kojer','Ko Jerry'),
('azizah','Azizah'),
('paksaep','Pak Saepudin'),
('pakmah','Pak Mahardika'),
('petrus','Petrus'),
('drhrajanti','drh. Rajanti'),
('rani','Rani'),
('rena','Rena'),
('risma','Risma'),
('ripana','Ripana'),
('sandika','Sandika'),
('sheila','Sheila'),
('sigit','Sigit'),
('drhnurma','drh. Nurmadinah'),
('pakali','Pak Ali'),
('masadi','Mas Adi'),
('masdewo','Mas Dewo'),
('maskadek','Mas Kadek'),
('anyo','Anyo'),
('masfauzi','Mas Fauzi'),
('masnoel','Mas Noel'),
('masdika','Mas Dika'),
('mia6','MIA 6'),
('kelasa','Kelas A'),
('temi','Temi'),
('pengky','Pengky'),
('anov','Anov'),
('clili','Ko Asiang - Ci Lili'),
('kbenny','Ko Benny - Ci Riri'),
('cersy','Ci Ersy'),
('celly','Ci Elly'),
('kuku','Kuku'),
('cyeyen','Ci Yeyen'),
('clinda','Ci Linda'),
('kadi','Ko Adi'),
('mmame','Papa Abeng - Mama Ame'),
('iiyong','Itnio Bambi - Iih Iyong'),
('kwawan','Ko Wawan - Teh Juwita'),
('mayang','Mayang'),
('kuotong','Ku Otong - Kim Yanah'),
('shindi','Shindi'),
('kadii','Ko Adi'),
('kimumi','Kim Umi'),
('cmila','Ci Mila'),
('kuuya','Ku Surya - Kim Puji'),
('sintha','Sintha')